config/routes.rb
require 'constraints/setup_wizard_constraint'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints Constraints::SetupWizardConstraint.new do
    get '/setup',   to: 'setup#start'

    get '/setup/user',    to: 'setup#user'
    post '/setup/user',    to: 'setup#createUser'

    get '/setup/network',    to: 'setup#network'
    post '/setup/network',    to: 'setup#configureNetwork'

    get '/setup/finish',     to: 'setup#finish'
    post '/setup/finish',    to: 'setup#doFinish'

    match '*path', to: 'setup#start', via: :get
    root 'setup#start'
  end

  constraints Clearance::Constraints::SignedIn.new do
    get 'cluster', to: 'cluster#index'
    post 'cluster/restart', to: 'cluster#restart'
    post 'cluster/stop', to: 'cluster#stop'

    post 'cluster/support-enable', to: 'cluster#enable_remote_support'
    post 'cluster/support-disable', to: 'cluster#disable_remote_support'

    get 'users', to: 'users#index'
    post 'users', to: 'users#create'
    post 'users/modify', to: 'users#modify'
    post 'users/delete', to: 'users#remove'

    get 'console', to: 'console#index'

    delete  '/logout',  to: 'sessions#destroy'

    match '/login' => redirect('/'), via: :get

    get 'network', to: 'network#index'
    post 'network/configure', to: 'network#configure'

    get 'ssl', to: 'ssl#index'
    post 'ssl/csr', to: 'ssl#csr'
    post 'ssl/cert', to: 'ssl#cert'

    match '*path', to: 'cluster#index', via: :get
    root 'cluster#index'
  end

  constraints Clearance::Constraints::SignedOut.new do
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'

    match '*path', to: 'sessions#new', via: :get

    root 'sessions#new'
  end

end

app/controllers/ssl_controller.rb
class SslController < ApplicationController
  before_action -> { redirect_unless_bolt_on("SSL") }
  
  def index
  end

  def csr

    csr_params = params[:csr]

    cmd = run_appliance_menu_cmd('certCSR', JSON.generate({"cname": csr_params['cname'], "org": csr_params['org'], "country": csr_params['country'] }))

    if cmd[:output]["status"] and !cmd[:output]["csr"].nil?
      send_data cmd[:output]["csr"], filename: 'appliance.csr'
      return
    else
      flash[:danger] = 'Encountered an error whilst generating CSR..'
      redirect_to ssl_path
    end 
  end

  def cert
    cert_content = params[:cert]['content']

    cmd = run_appliance_menu_cmd('certReplace', JSON.generate({"cert": cert_content}))

    if cmd[:output]["status"]
      flash[:success] = 'Replaced SSL certificate.'
    else
      flash[:danger] = 'Encountered an error whilst installing SSL cerificate..'
    end

    redirect_to ssl_path

  end
end

app/views/ssl/index.html.erb
<% content_for(:title) { 'SSL Management' } %>

<div class="row center mt-3" style="width: 90%;">
  <div class="col" style="min-width: 50%;"> 
    <div class="card d-flex center">
      <h5 class="card-header">Generate CSR</h5>
      <div class="card-body">
      <div class="row">
        <div class="mx-4 mb-2">Create a certificate signing request (CSR) for a site administrator to issue a SSL certificate for the appliance frontend.</div>
      </div> 
      <%= form_for :csr, as: :post, url: ssl_csr_path, html: { class: 'styled-form text-center w-100' } do |f| %>
        <div class="row mb-1">
          <div class="col-sm-4 form-label mt-1">
            <%= f.label :cname, 'Fully Qualified Domain Name:' %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :cname, class: 'form-control', required: true %>
          </div>
        </div>
        <div class="row mb-1">
          <div class="col-sm-4 form-label mt-1">
            <%= f.label :org, 'Organisation:' %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :org, class: 'form-control', required: true %>
          </div>
        </div>
        <div class="row mb-1">
          <div class="col-sm-4 form-label mt-1">
            <%= f.label :country, 'Country (2 letter code):' %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :country, class: 'form-control', required: true %>
          </div>
        </div>
        <%= f.submit "Generate", disable_with: 'Generating...', class: 'btn btn-primary center mt-3' %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card d-flex center">
      <h5 class="card-header">Upload Certificate</h5>
      <div class="card-body">
      <div class="row">
        <div class="mx-4 mb-2">Upload a new SSL certificate to use for the appliance front end.</div>
      </div>
        <%= form_for :cert, as: :post, url: ssl_cert_path, html: { class: 'styled-form text-center w-100' } do |f| %>
        <div class="row mb-1">
          <div class="col-sm-2 form-label mt-1">
            <%= f.label :content, 'Certificate:' %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :content, class: 'form-control', required: true, style: 'min-height: 350px' %>
          </div>
        </div>
        <%= f.submit "Upload", disable_with: 'Uploading...', class: 'btn btn-primary center mt-3' %>
        <% end %>
      </div>
    </div>
  </div>
</div>